zuul:
  prefix: /api
  routes:
    item-service: /item/**
    user-service: /user/**
    auth-service: /auth/**
    cart-service: /cart/**
    order-service: /order-service/**
    upload-service:
      path: /upload/**
      service: upload-service
      strip-prefix: false
    search-service: /search/**
  sensitive-headers:
  add-host-header: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 7000
ribbon:
  connetTimeout: 500
  readTimeout: 5000

ly:
  jwt:
    pubKeyPath: /Users/bystander/id_rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称
  filter:
    allowPaths:
    - /api/auth
    - /api/search
    - /api/user/register
    - /api/user/check
    - /api/user/code
    - /api/item

