server:
  port: 8083
spring:
  application:
    name: money-service
  datasource:
    url: jdbc:mysql://localhost:3306/oa
    username: root
    password:
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

mybatis:
  type-aliases-package: com.leyou.money.pojo